#!/bin/bash

if [ "$( psql $DB_NAME -h $DB_HOST -U $DB_USER -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    # Installing fastapi demo failed when mail is alreay installed
    # so install it first
    click-odoo-initdb -n $DB_NAME -m fastapi --no-cache
    odoo -i shopinvader_docker_demo -d $DB_NAME --stop-after-init
fi
