#!/usr/bin/env python3
import os
import subprocess
import sys


def check_call(cmd):
    print(" ".join(cmd))
    sys.stdout.flush()
    subprocess.check_call(cmd)


db_name = os.getenv("DB_NAME")

if db_name:
    check_call(
        [
            "click-odoo-initdb",
            "--unless-exists",
            "-n",
            db_name,
            "-m shopinvader_docker_demo",
            "--no-cache",
        ]
    )
